imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Test\UserBundle\Entity\User

fos_elastica:
    serializer: ~
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        api:
            types:
                user:
                    mappings:
                        username:
                            type: string
                        nick:
                            type: string
                        email:
                            type: string
                    persistence:
                        driver: orm
                        model: Test\UserBundle\Entity\User
                        provider: ~
                        finder: ~
#            settings:
#                index:
#                    analysis:
#                        analyzer:
#                            my_analyzer:
#                                type: custom
#                                tokenizer: lowercase
#                                filter   : [my_ngram]
#                        filter:
#                            my_ngram:
#                                type: "nGram"
#                                min_gram: 1
#                                max_gram: 20

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
