security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    demo: { password: demo, roles: 'ROLE_USER' }

    firewalls:
        main:
            pattern:    /.*
            http_basic: true
            logout:     true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }